services:
    web:
        container_name: anime_wiki_web
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            postgresql:
                condition: service_healthy
            api:
                condition: service_started
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
        networks:
            - next-node

    api:
        container_name: anime_wiki_api
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            postgresql:
                condition: service_healthy
        volumes:
            - ./backend:/app/backend
            - /app/backend/node_modules
        env_file:
            - .env

    postgresql:
        image: postgres
        container_name: anime_wiki_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: anime_wiki
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U root']
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    next-node:
    node-postgres:

volumes:
    postgres_data:
